// Snapshot of the pre-event-types DEFAULT_DESIGN (the Spanish wedding). Used by
// tests to prove the WEDDING template and normalizeDesign preserve it exactly.
import type { InvitationDesign } from '../../types/sigil.types';

export const LEGACY_WEDDING_DEFAULT: InvitationDesign = {
  id: 'design-default',
  title: 'Untitled Invitation',
  paperTexture: 'parchment',
  paperLuminance: 'LIGHT',
  envelopeStyle: 'CLASSIC',
  textBlocks: [
    {
      id: 'tb-headline',
      content: 'Oscar & Rocio',
      fontFamily: "'Cormorant Garamond', serif",
      fontSize: 2.2,
      fontStyle: 'italic',
      fontWeight: 400,
      color: 'DARK_INK',
      textAlign: 'center',
      letterSpacing: 0.04,
      lineHeight: 1.25,
      marginTop: 0,
    },
  ],
  borderStyle: 'deckled',
  backgroundColor: 'var(--paper-parchment)',
  rsvpFormConfig: {
    requireMealPreference: false,
    requireDietaryRestrictions: false,
    allowPlusOnes: false,
    customNotesLabel: null,
  },
  countdownTarget: '2026-09-17T18:00:00',
  itinerary: [
    {
      id: 'itin-1',
      title: 'Ceremonia Religiosa',
      locationName: 'Parroquia Nuestra Señora de Aránzazu, Constitución 950, San Fernando',
      time: '18:00',
      mapLink: 'https://maps.google.com',
    },
    {
      id: 'itin-2',
      title: 'Recepción',
      locationName: 'Palacio Sans Souci, Paz 705',
      time: '19:00',
      mapLink: 'https://maps.google.com',
    },
  ],
  colorPalette: ['#4f5d47', '#a08e7c', '#4c4844', '#dfb88e', '#e8e5c8'],
  dressCodeText: 'Formal',
  dressCodeMaleHeading: 'Ellos',
  dressCodeMaleText: 'Traje formal',
  dressCodeMaleSubtext: 'Favor de evitar color azul marino',
  dressCodeMaleAvoidColors: ['#003366'],
  dressCodeFemaleHeading: 'Ellas',
  dressCodeFemaleText: 'Vestido largo',
  dressCodeFemaleSubtext: 'Favor de evitar colores blanco, beige o colores pasteles',
  dressCodeFemaleAvoidColors: ['#ffffff', '#f5f5dc', '#ffd1dc'],
  registryText: 'Su compañía es lo más importante. Si desean hacernos un obsequio, lo recibiremos con mucho cariño.',
  registryLink: '',
  registryImageScale: 100,
  closedEnvelopeImage: '',
  headerImageScale: 100,
  openedEnvelopeImage: '',
  openedEnvelopeImageScale: 100,
  stickerImage: '',
  sealSize: 75,
  musicUrl: '',
  paperSaturate: 1.0,
  language: 'ES',
};
